apiVersion: v1
kind: Secret
metadata:
  name: yuuvissecret
  namespace: yuuvis
type: kubernetes.io/basic-auth
stringData:
  username: prosozTest
  password: sd43wGFds32(%1
  yuuvisusername: root
  yuuvispassword: optimalsystem
  sslenabled: '{{ .Values.sslenabled }}'
  selfsignedcertificate: '{{ .Values.selfsignedcertificate }}'
  keystorecn: '{{ .Values.keystorecn }}'
  keystorepath: '{{ .Values.keystorepath }}'
  keystorepassword: '{{ .Values.keystorepassword }}'

