serverurl: http://192.168.178.91
serverport: 30036
tenant: yuuvistest
sslenabled: true
apiport: 443
selfsignedcertificate: true
keystorecn: 192.168.178.91
keystorepath: yuuviskeystoremacpro.jks
keystorepassword: secret
yuuvisusername: prosoz
yuuvispassword: Freund_$$
