- name: Install nexus secrets
  kubernetes.core.helm:
    name: nexus
    namespace: yuuvis
    chart_ref: ../yuuvisvapi/nexus
    kubeconfig_path: "{{ kubeconfig }}"
    create_namespace: True
    wait: true
- name: Install yuuvis-v-api
  kubernetes.core.helm:
    name: yuuvis-v-api
    namespace: yuuvis
    chart_ref: ../yuuvisvapi/api
    kubeconfig_path: "{{ kubeconfig }}"
    create_namespace: True
    wait: true
    force: true
    values_files: ../yuuvisvapi-values/values.yaml
