- name: Install csi-raid dynamic storage provisioner
  kubernetes.core.helm:
    name: dynamicstorageprovisioner
    namespace: kube-system
    chart_ref: ../csi-raid/dynamic-storage-provisioner
    kubeconfig_path: "{{ kubeconfig }}"
    create_namespace: True
    wait: true
    force: true
    values_files: ../csi-raid-values/values.yaml
